<h1><center>PYTHON FOR MACHINE LEARNING (INT-215)</center></h1>
<h1><center>CA-1</center></h1>
<h1><center>Set-1</center></h1>

### Q-1 You are given a list of numbers. Using NumPy, create an array of these numbers and calculate the
### mean, median and standard deviation of the array. 


In [1]:
import numpy as np

numbers = [1, 2, 3, 4, 5]

arr = np.array(numbers)

# calculate the mean
mean = np.mean(arr)

# calculate the median
median = np.median(arr)

# calculate the standard deviation
std_dev = np.std(arr)

print("Array:", arr)
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std_dev)

Array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951


### Q-2 You are given a 2D array of numbers. Using slicing and indexing operations, extract the values
### from the second row and third column. 

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# extract the value from the second row and third column
value = arr[1][2] #Indexing
value1=arr[1,2] #Indexing
value2 = arr[1:2, 2:3] #Slicing

print("Value:", value)
print("Value:", value1)
print("Value:", value2)

Value: 6
Value: 6
Value: [[6]]


### Q-3 You have two arrays of equal length. Using NumPy, calculate the dot product of these arrays 

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# calculate the dot product
dot_product = np.dot(arr1, arr2)

print("Dot product:", dot_product)

Dot product: 32


### Q-4 You have an array of shape (3, 4). Using NumPy, reshape it into an array of shape (2, 6). 

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# reshape the array to shape (2, 6)
new_arr = arr.reshape((2, 6))


print("Original array:\n", arr)
print("Reshaped array:\n", new_arr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Q-5 You have two arrays of shape (2, 3) and (2, 4). Using NumPy, stack them horizontally and vertically respectively. 


In [5]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

# stack the arrays horizontally
horizontal_stack = np.hstack((arr1, arr2))

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Horizontally stacked array:\n", horizontal_stack)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9 10]
 [11 12 13 14]]
Horizontally stacked array:
 [[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]]


In [6]:
# stack the arrays vertically
vertical_stack = np.vstack((arr1, arr2))
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Vertically stacked array:\n", vertical_stack)
# Two arrays of dimensions (2,3) adn (2,4) cannot be vertically stacked on
#top of each other as they dont have the same number of coloumns

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

### Q-6 You have an array of shape (4, 4). Using NumPy, split it into four equal parts.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# split the array into 4 equal parts
split_arr = np.split(arr, 2)
split_arr = [np.split(sub_arr, 2, axis=1) for sub_arr in split_arr]
split_arr = [elem for sublist in split_arr for elem in sublist]

print("Original array:\n", arr)
for i, sub_arr in enumerate(split_arr):
    print("Split array", i+1, ":\n", sub_arr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Split array 1 :
 [[1 2]
 [5 6]]
Split array 2 :
 [[3 4]
 [7 8]]
Split array 3 :
 [[ 9 10]
 [13 14]]
Split array 4 :
 [[11 12]
 [15 16]]


### Q-7 You are given an array of numbers. Using NumPy, calculate the exponential of each element in
### the array. 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# calculate the exponential of each element
exp_arr = np.exp(arr)

print("Original array:", arr)
print("Exponential array:", exp_arr)

Original array: [1 2 3 4 5]
Exponential array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Q-8 You have two arrays of equal length. Using NumPy, perform element-wise addition, subtraction,
### multiplication and division on these arrays. 

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

# perform element-wise arithmetic operations
add_arr = arr1 + arr2
sub_arr = arr1 - arr2
mul_arr = arr1 * arr2
div_arr = arr1 / arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition:", add_arr)
print("Subtraction:", sub_arr)
print("Multiplication:", mul_arr)
print("Division:", div_arr)

Array 1: [1 2 3 4 5]
Array 2: [ 2  4  6  8 10]
Addition: [ 3  6  9 12 15]
Subtraction: [-1 -2 -3 -4 -5]
Multiplication: [ 2  8 18 32 50]
Division: [0.5 0.5 0.5 0.5 0.5]


### Q-9 You have two arrays of shape (2, 2). Using NumPy, calculate the determinant of the product of
### these two arrays.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# calculate the product of the two arrays
product = np.dot(arr1, arr2)

# calculate the determinant of the product
determinant = np.linalg.det(product)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Product:\n", product)
print("Determinant of product:", determinant)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Product:
 [[19 22]
 [43 50]]
Determinant of product: 4.000000000000008


### Q-10  You are given a list of names and their corresponding ages. Using Pandas, create a series of these
### data.

In [ ]:
import pandas as pd

names = ["Alice", "Bob", "Charlie", "David"]
ages = [25, 30, 35, 40]

# create a Pandas Series from the list of names and ages
series = pd.Series(ages, index=names)

print(series)

Alice      25
Bob        30
Charlie    35
David      40
dtype: int64


### Q-11 You have a data frame containing the names, ages and grades of students. Using indexing and
### selection operations, extract the grades of students who are above 18 years old.

In [ ]:
import pandas as pd

data = {"Name": ["Alice", "Bob", "Charlie", "David"],
        "Age": [25, 30, 17, 40],
        "Grade": [90, 85, 75, 95]}
df = pd.DataFrame(data)

# extract the grades of students who are above 18 years old
grades_above_18 = df.loc[df["Age"] > 18, "Grade"]

print(grades_above_18)

0    90
1    85
3    95
Name: Grade, dtype: int64


### Q-12 You have two data frames containing the names and grades of students from two different
### classes. Using Pandas, merge these data frames on the basis of the names of the students.

In [ ]:
import pandas as pd

data1 = {"Name": ["Alice", "Bob", "Charlie", "David"],
         "Grade": [90, 85, 75, 95]}
df1 = pd.DataFrame(data1)

data2 = {"Name": ["Alice", "Bob", "Eve", "Frank"],
         "Grade": [80, 70, 65, 75]}
df2 = pd.DataFrame(data2)

merged_df = pd.merge(df1, df2, on="Name", suffixes=("_class1", "_class2"))

print(merged_df)

    Name  Grade_class1  Grade_class2
0  Alice            90            80
1    Bob            85            70


 ###   Q-13 You have a data frame containing the names and ages of students from one class. Using Pandas,
### append the data frame with the names and ages of students from another class. 

In [1]:
import pandas as pd

data1 = {"Name": ["Alice", "Bob", "Charlie"],
         "Age": [20, 18, 19]}
df1 = pd.DataFrame(data1)

data2 = {"Name": ["David", "Eve", "Frank"],
         "Age": [21, 22, 20]}
df2 = pd.DataFrame(data2)

appended_df = pd.concat([df1, df2], ignore_index=True)

print(appended_df)


      Name  Age
0    Alice   20
1      Bob   18
2  Charlie   19
3    David   21
4      Eve   22
5    Frank   20
